### ISSUE TITLE
Not opening the Unlocker

### ISSUE THREAD

**Issue by orangejuiceondiscord** [Cyuubi/AlphaUnlocker#1]
I am opening Fortnite Alpha and I inject the dll but nothing is connected and after I get in it doesn't work. I am using UE4 Unlocker or UUU302.

**Comment by AquaPlaysYT** [comment]
You said your using UE4 Unlocker? Why are you not using Alpha Unlocker..?

**Comment by orangejuiceondiscord** [comment]
I am using the AlphaUnlocker.dll file

**Comment by AquaPlaysYT** [comment]
Oh i see, you mean injecting with UUU My bad, yeah id wait for cyuubi to respond

**Comment by Cyuubi** [comment]
You need to inject the DLL at startup.
